/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import MYSQLSERVER.MySQLServer;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class AddFriendFrom extends javax.swing.JFrame {

    
    private MySQLServer database;
    private int mauser;
    
    public AddFriendFrom(int mauser) {
        initComponents();
        database = new MySQLServer();
        this.mauser = mauser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContain = new javax.swing.JPanel();
        lblNhap = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        lblBD = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGTinh = new javax.swing.JLabel();
        lblGT = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THÊM BẠN");
        setResizable(false);

        PanelContain.setBackground(new java.awt.Color(153, 255, 255));

        lblNhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNhap.setText("Nhập Tên:");

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        lblBD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBD.setText("Biệt Danh:");

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblGTinh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGTinh.setText("Giới Tính:");

        lblGT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setText("Kết Bạn");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelContainLayout = new javax.swing.GroupLayout(PanelContain);
        PanelContain.setLayout(PanelContainLayout);
        PanelContainLayout.setHorizontalGroup(
            PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(PanelContainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelContainLayout.createSequentialGroup()
                        .addComponent(lblNhap)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContainLayout.createSequentialGroup()
                        .addGroup(PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBD)
                            .addComponent(lblGTinh))
                        .addGap(18, 18, 18)
                        .addGroup(PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelContainLayout.createSequentialGroup()
                                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(PanelContainLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        PanelContainLayout.setVerticalGroup(
            PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhap)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGTinh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PanelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnThoat))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            database.Connection();
            
            String str = "Select GioiTinh, Avatar from Users where NameUser = '" + txtSearch.getText() + "';";
            ResultSet rs = database.executeQuery(str);
            while(rs.next()){
                if(rs.getBoolean("GioiTinh"))
                    lblGT.setText("Nam");
                else lblGT.setText("Nữ");
                ImageIcon icon = EditImage.XuLyAnh.Edit_Img(rs.getString("Avatar"), lblAvatar);
                lblAvatar.setIcon(icon);
            }
            lblName.setText(txtSearch.getText());
            
            database.Close();
        }catch(Exception e){
            e.printStackTrace();
        }
        btnTimKiem.setEnabled(false);
        btnAdd.setEnabled(true);
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        int maF = 0;
        
        try {
            database.Connection();
            
            String str = "Select MaUser from Users where NameUser = '" + lblName.getText() + "';";
            ResultSet rs = database.executeQuery(str);
            while(rs.next()){
                maF = rs.getInt(1);
            }
            
            String s = "Insert into Friend values(" + this.mauser + ", " + maF + ");";
            String s1 = "Insert into Friend values(" + maF + ", " + this.mauser + ");";
            database.executeNonQuery(s);
            database.executeNonQuery(s1);
            
            database.Close();
        }catch(Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "Đã Thêm Bạn Thành Công.", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        btnTimKiem.setEnabled(true);
        btnAdd.setEnabled(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContain;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblBD;
    private javax.swing.JLabel lblGT;
    private javax.swing.JLabel lblGTinh;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNhap;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
