/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import CLIENT.Users;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author ADMIN
 */
public class CapNhat_From extends javax.swing.JFrame {

    private String name;
    private String gioitinh;
    private String ngaysinh;
    private String avatar;
    private Users user;
    
    /**
     * Creates new form SignUpFrom
     */
    public CapNhat_From() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Comtain = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblGT = new javax.swing.JLabel();
        cmbGT = new javax.swing.JComboBox<>();
        lblNS = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        btnDangKy = new javax.swing.JButton();
        lblDangNhap = new javax.swing.JLabel();
        btnChonAvatar = new javax.swing.JButton();
        lbl_Avatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatBox");
        setResizable(false);

        Panel_Comtain.setBackground(new java.awt.Color(204, 255, 255));

        lblHeading.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblHeading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-signup-64.png"))); // NOI18N
        lblHeading.setText("Cập nhật Thông Tin ");

        lblHoTen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHoTen.setText("Họ Tên:");

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblGT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGT.setText("Giới Tính:");

        cmbGT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        lblNS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNS.setText("Ngày Sinh:");

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnDangKy.setBackground(new java.awt.Color(255, 255, 255));
        btnDangKy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDangKy.setText("Cập Nhật");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        lblDangNhap.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDangNhap.setText("Đăng Nhập ==>");
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });

        btnChonAvatar.setBackground(new java.awt.Color(255, 255, 255));
        btnChonAvatar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChonAvatar.setText("Chọn Avatar");
        btnChonAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAvatarActionPerformed(evt);
            }
        });

        lbl_Avatar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Avatar.setOpaque(true);

        javax.swing.GroupLayout Panel_ComtainLayout = new javax.swing.GroupLayout(Panel_Comtain);
        Panel_Comtain.setLayout(Panel_ComtainLayout);
        Panel_ComtainLayout.setHorizontalGroup(
            Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ComtainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(lblDangNhap)
                .addGap(69, 69, 69))
            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblHeading)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ComtainLayout.createSequentialGroup()
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChonAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                                .addComponent(lblNS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                                .addComponent(lblGT)
                                .addGap(18, 18, 18)
                                .addComponent(cmbGT, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                                .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127))
        );
        Panel_ComtainLayout.setVerticalGroup(
            Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGT))
                        .addGap(56, 56, 56)
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNS)))
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnChonAvatar)
                        .addGap(119, 119, 119)
                        .addComponent(lblDangNhap)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ComtainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Comtain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Comtain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        LoginFrom login = new LoginFrom();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_lblDangNhapMouseClicked

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        
        int GT = 1;

        name = txtHoTen.getText();
        gioitinh = cmbGT.getItemAt(cmbGT.getSelectedIndex());
        System.out.println(gioitinh);
        ngaysinh = txtNgaySinh.getText();
        
        if(gioitinh.equals("Nam"))
            GT = 1;
        else if(gioitinh.equals("Nữ")){
            GT = 0;
        }
        
        user = new Users(name, GT, ngaysinh, avatar);
        try {
            user.SaveUser();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CapNhat_From.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CapNhat_From.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Đã cập nhật thông tin thành công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnChonAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAvatarActionPerformed
        JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("Hình Ảnh", "jpg", "png");
        filechooser.setFileFilter(imgFilter);
        filechooser.setMultiSelectionEnabled(false);
        int n = filechooser.showDialog(this, "Chọn Ảnh");
        if(n == JFileChooser.APPROVE_OPTION){
            File f = filechooser.getSelectedFile();
            avatar = f.getAbsolutePath();
            ImageIcon icon = EditImage.XuLyAnh.Edit_Img(avatar, lbl_Avatar);
            lbl_Avatar.setIcon(icon);
            
            System.out.println(avatar);
        }
    }//GEN-LAST:event_btnChonAvatarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Comtain;
    private javax.swing.JButton btnChonAvatar;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JComboBox<String> cmbGT;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblGT;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblNS;
    private javax.swing.JLabel lbl_Avatar;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
