/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import MYSQLSERVER.MySQLServer;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class ClientFrom extends javax.swing.JFrame {


    private HashMap<String, String> friends;
    private int numFri = 0;
    private int mauser;
    private String nameuser;
    private String gioitinh;
    private String ngaysinh;
    private String avatar;
    private DataOutputStream out;
    private DataInputStream in;
    private String yeucau;
    private MySQLServer database;
    
    Thread receiver;
    
    
    public ClientFrom(DataOutputStream out, DataInputStream in, int mauser, String nameuser, String gioitinh, String ngaysinh, String avatar) {
        this.out = out;
        this.in = in;
        this.mauser = mauser;
        this.nameuser = nameuser;
        this.gioitinh = gioitinh;
        this.ngaysinh = ngaysinh;
        this.avatar = avatar;
        database = new MySQLServer();
        
        initComponents(); 
        SetUp();
        lblName.setText("ChatBox Xin Chào Bạn !!!");
        receiver = new Thread(new Receiver(in));
        receiver.start();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContain = new javax.swing.JPanel();
        PanelChucNang = new javax.swing.JPanel();
        lblAvatar_User = new javax.swing.JLabel();
        lbl_Chat = new javax.swing.JLabel();
        lbl_Group = new javax.swing.JLabel();
        lbl_Add = new javax.swing.JLabel();
        lbl_Logout = new javax.swing.JLabel();
        ScrollPanel_listFiend = new javax.swing.JScrollPane();
        Panel_ListFriend = new javax.swing.JPanel();
        Panel_Contain = new javax.swing.JPanel();
        Panel_Name_Friend = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAvatar_Friend = new javax.swing.JLabel();
        Panel_NhapText = new javax.swing.JPanel();
        txtMessage = new javax.swing.JTextField();
        ScrollPane_Emojis = new javax.swing.JScrollPane();
        Panel_Emojis = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        Label14 = new javax.swing.JLabel();
        Label15 = new javax.swing.JLabel();
        Label16 = new javax.swing.JLabel();
        Label17 = new javax.swing.JLabel();
        Label18 = new javax.swing.JLabel();
        Label19 = new javax.swing.JLabel();
        Label20 = new javax.swing.JLabel();
        Label21 = new javax.swing.JLabel();
        Label23 = new javax.swing.JLabel();
        Label24 = new javax.swing.JLabel();
        Label25 = new javax.swing.JLabel();
        Label26 = new javax.swing.JLabel();
        Label27 = new javax.swing.JLabel();
        Label28 = new javax.swing.JLabel();
        Label29 = new javax.swing.JLabel();
        Label22 = new javax.swing.JLabel();
        lbl_ChonFile = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        ScrollPane_Chat = new javax.swing.JScrollPane();
        PanelChat = new javax.swing.JPanel();
        Panel_Search = new javax.swing.JPanel();
        lbl_Heading = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDSBan = new javax.swing.JButton();
        btnDSNhom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatBox");
        setResizable(false);

        panelContain.setBackground(new java.awt.Color(255, 255, 255));

        PanelChucNang.setBackground(new java.awt.Color(153, 255, 255));
        PanelChucNang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAvatar_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatar_UserMouseClicked(evt);
            }
        });

        lbl_Chat.setBackground(new java.awt.Color(153, 255, 255));
        lbl_Chat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-messages-60.png"))); // NOI18N
        lbl_Chat.setOpaque(true);
        lbl_Chat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ChatMouseClicked(evt);
            }
        });

        lbl_Group.setBackground(new java.awt.Color(153, 255, 255));
        lbl_Group.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-group-64 (1).png"))); // NOI18N
        lbl_Group.setOpaque(true);
        lbl_Group.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_GroupMouseClicked(evt);
            }
        });

        lbl_Add.setBackground(new java.awt.Color(153, 255, 255));
        lbl_Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-user-group-man-man-50.png"))); // NOI18N
        lbl_Add.setOpaque(true);
        lbl_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AddMouseClicked(evt);
            }
        });

        lbl_Logout.setBackground(new java.awt.Color(153, 255, 255));
        lbl_Logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-logout-50.png"))); // NOI18N
        lbl_Logout.setOpaque(true);
        lbl_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelChucNangLayout = new javax.swing.GroupLayout(PanelChucNang);
        PanelChucNang.setLayout(PanelChucNangLayout);
        PanelChucNangLayout.setHorizontalGroup(
            PanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAvatar_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Chat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Group, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
            .addComponent(lbl_Add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
        PanelChucNangLayout.setVerticalGroup(
            PanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvatar_User, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbl_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Group, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        Panel_ListFriend.setBackground(new java.awt.Color(255, 255, 255));
        Panel_ListFriend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_ListFriend.setLayout(new javax.swing.BoxLayout(Panel_ListFriend, javax.swing.BoxLayout.Y_AXIS));
        ScrollPanel_listFiend.setViewportView(Panel_ListFriend);

        Panel_Contain.setBackground(new java.awt.Color(255, 255, 255));

        Panel_Name_Friend.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Name_Friend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 51, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAvatar_Friend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Panel_Name_FriendLayout = new javax.swing.GroupLayout(Panel_Name_Friend);
        Panel_Name_Friend.setLayout(Panel_Name_FriendLayout);
        Panel_Name_FriendLayout.setHorizontalGroup(
            Panel_Name_FriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Name_FriendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvatar_Friend, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Name_FriendLayout.setVerticalGroup(
            Panel_Name_FriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Name_FriendLayout.createSequentialGroup()
                .addGroup(Panel_Name_FriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar_Friend, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_NhapText.setBackground(new java.awt.Color(255, 255, 255));
        Panel_NhapText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMessage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        ScrollPane_Emojis.setBackground(new java.awt.Color(255, 255, 255));

        Panel_Emojis.setBackground(new java.awt.Color(255, 255, 255));

        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (1).png")); // NOI18N
        Label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label1MouseClicked(evt);
            }
        });

        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label2.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (10).png")); // NOI18N
        Label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label2MouseClicked(evt);
            }
        });

        Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label3.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (11).png")); // NOI18N
        Label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label3MouseClicked(evt);
            }
        });

        Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label4.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (12).png")); // NOI18N
        Label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label4MouseClicked(evt);
            }
        });

        Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label5.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (13).png")); // NOI18N
        Label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label5MouseClicked(evt);
            }
        });

        Label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label6.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (14).png")); // NOI18N
        Label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label6MouseClicked(evt);
            }
        });

        Label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label7.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (15).png")); // NOI18N
        Label7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label7MouseClicked(evt);
            }
        });

        Label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label8.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (16).png")); // NOI18N
        Label8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label8MouseClicked(evt);
            }
        });

        Label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label9.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (17).png")); // NOI18N
        Label9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label9MouseClicked(evt);
            }
        });

        Label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label10.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (18).png")); // NOI18N
        Label10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label10MouseClicked(evt);
            }
        });

        Label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label11.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (19).png")); // NOI18N
        Label11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label11MouseClicked(evt);
            }
        });

        Label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label12.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (20).png")); // NOI18N
        Label12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label12MouseClicked(evt);
            }
        });

        Label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label13.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (21).png")); // NOI18N
        Label13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label13MouseClicked(evt);
            }
        });

        Label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label14.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-broken-heart-32.png")); // NOI18N
        Label14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label14MouseClicked(evt);
            }
        });

        Label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label15.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-facebook-like-skin-type-1-32 (1).png")); // NOI18N
        Label15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label15MouseClicked(evt);
            }
        });

        Label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label16.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-favorite-32.png")); // NOI18N
        Label16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label16MouseClicked(evt);
            }
        });

        Label17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label17.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-facebook-like-skin-type-2-32.png")); // NOI18N
        Label17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label17MouseClicked(evt);
            }
        });

        Label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label18.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-facebook-like-skin-type-1-32.png")); // NOI18N
        Label18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label18MouseClicked(evt);
            }
        });

        Label19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label19.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-pixel-heart-32.png")); // NOI18N
        Label19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label19MouseClicked(evt);
            }
        });

        Label20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label20.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-heart-32.png")); // NOI18N
        Label20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label20MouseClicked(evt);
            }
        });

        Label21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label21.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-growing-heart-32.png")); // NOI18N
        Label21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label21MouseClicked(evt);
            }
        });

        Label23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label23.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (2).png")); // NOI18N
        Label23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label23MouseClicked(evt);
            }
        });

        Label24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label24.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (3).png")); // NOI18N
        Label24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label24MouseClicked(evt);
            }
        });

        Label25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label25.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (4).png")); // NOI18N
        Label25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label25MouseClicked(evt);
            }
        });

        Label26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label26.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (5).png")); // NOI18N
        Label26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label26MouseClicked(evt);
            }
        });

        Label27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label27.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (6).png")); // NOI18N
        Label27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label27MouseClicked(evt);
            }
        });

        Label28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label28.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (7).png")); // NOI18N
        Label28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label28MouseClicked(evt);
            }
        });

        Label29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label29.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (8).png")); // NOI18N
        Label29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label29MouseClicked(evt);
            }
        });

        Label22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label22.setIcon(new javax.swing.ImageIcon("D:\\NetBeans\\ChatBox\\src\\Image\\Emojis\\icons8-emoji-32 (9).png")); // NOI18N
        Label22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_EmojisLayout = new javax.swing.GroupLayout(Panel_Emojis);
        Panel_Emojis.setLayout(Panel_EmojisLayout);
        Panel_EmojisLayout.setHorizontalGroup(
            Panel_EmojisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EmojisLayout.createSequentialGroup()
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label16)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        Panel_EmojisLayout.setVerticalGroup(
            Panel_EmojisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EmojisLayout.createSequentialGroup()
                .addGroup(Panel_EmojisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label1)
                    .addComponent(Label2)
                    .addComponent(Label3)
                    .addComponent(Label4)
                    .addComponent(Label5)
                    .addComponent(Label6)
                    .addComponent(Label7)
                    .addComponent(Label8)
                    .addComponent(Label9)
                    .addComponent(Label10)
                    .addComponent(Label11)
                    .addComponent(Label12)
                    .addComponent(Label13)
                    .addComponent(Label14)
                    .addComponent(Label15)
                    .addComponent(Label16)
                    .addComponent(Label17)
                    .addComponent(Label18)
                    .addComponent(Label19)
                    .addComponent(Label20)
                    .addComponent(Label21)
                    .addComponent(Label23)
                    .addComponent(Label24)
                    .addComponent(Label25)
                    .addComponent(Label26)
                    .addComponent(Label27)
                    .addComponent(Label28)
                    .addComponent(Label29)
                    .addComponent(Label22))
                .addGap(0, 151, Short.MAX_VALUE))
        );

        ScrollPane_Emojis.setViewportView(Panel_Emojis);

        lbl_ChonFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ChonFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-link-32.png"))); // NOI18N
        lbl_ChonFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ChonFileMouseClicked(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(255, 255, 255));
        btnSend.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-send-32.png"))); // NOI18N
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_NhapTextLayout = new javax.swing.GroupLayout(Panel_NhapText);
        Panel_NhapText.setLayout(Panel_NhapTextLayout);
        Panel_NhapTextLayout.setHorizontalGroup(
            Panel_NhapTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NhapTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_NhapTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_NhapTextLayout.createSequentialGroup()
                        .addComponent(lbl_ChonFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPane_Emojis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_NhapTextLayout.setVerticalGroup(
            Panel_NhapTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NhapTextLayout.createSequentialGroup()
                .addGroup(Panel_NhapTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_NhapTextLayout.createSequentialGroup()
                        .addGroup(Panel_NhapTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_ChonFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(ScrollPane_Emojis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        ScrollPane_Chat.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ScrollPane_Chat.setAutoscrolls(true);

        PanelChat.setBackground(new java.awt.Color(255, 255, 255));
        PanelChat.setLayout(new javax.swing.BoxLayout(PanelChat, javax.swing.BoxLayout.Y_AXIS));
        ScrollPane_Chat.setViewportView(PanelChat);

        javax.swing.GroupLayout Panel_ContainLayout = new javax.swing.GroupLayout(Panel_Contain);
        Panel_Contain.setLayout(Panel_ContainLayout);
        Panel_ContainLayout.setHorizontalGroup(
            Panel_ContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_NhapText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_ContainLayout.createSequentialGroup()
                .addGroup(Panel_ContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ContainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel_Name_Friend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ScrollPane_Chat))
                .addContainerGap())
        );
        Panel_ContainLayout.setVerticalGroup(
            Panel_ContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ContainLayout.createSequentialGroup()
                .addComponent(Panel_Name_Friend, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_NhapText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Panel_Search.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_Heading.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_Heading.setText("Tìm Bạn Bè, Nhóm:");

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDSBan.setBackground(new java.awt.Color(255, 255, 255));
        btnDSBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDSBan.setText("DS Bạn");
        btnDSBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSBanActionPerformed(evt);
            }
        });

        btnDSNhom.setBackground(new java.awt.Color(255, 255, 255));
        btnDSNhom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDSNhom.setText("DS Nhóm");
        btnDSNhom.setEnabled(false);

        javax.swing.GroupLayout Panel_SearchLayout = new javax.swing.GroupLayout(Panel_Search);
        Panel_Search.setLayout(Panel_SearchLayout);
        Panel_SearchLayout.setHorizontalGroup(
            Panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SearchLayout.createSequentialGroup()
                .addComponent(lbl_Heading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Panel_SearchLayout.createSequentialGroup()
                .addComponent(txtSearch)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(80, 80, 80))
            .addGroup(Panel_SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDSBan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDSNhom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_SearchLayout.setVerticalGroup(
            Panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Heading)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDSBan)
                    .addComponent(btnDSNhom))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout panelContainLayout = new javax.swing.GroupLayout(panelContain);
        panelContain.setLayout(panelContainLayout);
        panelContainLayout.setHorizontalGroup(
            panelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainLayout.createSequentialGroup()
                .addComponent(PanelChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Contain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollPanel_listFiend, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(Panel_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        panelContainLayout.setVerticalGroup(
            panelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Contain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContainLayout.createSequentialGroup()
                .addGroup(panelContainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContainLayout.createSequentialGroup()
                        .addComponent(Panel_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPanel_listFiend, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Hàm set up cho avatar của user
    public final void SetUp(){
        
      ImageIcon icon = EditImage.XuLyAnh.Edit_Img(avatar, lblAvatar_User);
      lblAvatar_User.setIcon(icon);  
        
    }
    
    
    
    //Hàm set up cho avatar và tên của Friend
    public final void SetUp_PanelFriend(String name, String avatar) {
        lblName.setText(name);
        ImageIcon icon = EditImage.XuLyAnh.Edit_Img(avatar, lblAvatar_Friend);
        lblAvatar_Friend.setIcon(icon); 
    }
    
    //Xử lý sự kiện khi chọn vào một chức năng
    public final void setFoucus(JLabel label){
        label.setBackground(Color.WHITE);
        //label.setBackground(new Color(153, 255, 255));

        label.setBorder(BorderFactory.createLoweredBevelBorder());
    }
    
    //Xử lý sự kiện cho việc thoát khỏi một nút chức năng
    public final void resetFoucus(JLabel label1, JLabel label2, JLabel label3){
        label1.setBackground(new Color(153, 255, 255));
        label1.setBorder(BorderFactory.createEmptyBorder());
        
        label2.setBackground(new Color(153, 255, 255));
        label2.setBorder(BorderFactory.createEmptyBorder());
        
        label3.setBackground(new Color(153, 255, 255));
        label3.setBorder(BorderFactory.createEmptyBorder());
    }
    
    //Xử lý sự kiện chatFirend
    private void lbl_ChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChatMouseClicked
        yeucau = "ChatWithFriend";
        setFoucus(lbl_Chat);
        resetFoucus(lbl_Group, lbl_Add, lbl_Logout);
    }//GEN-LAST:event_lbl_ChatMouseClicked

    //Xử lý sự liện nút gữi
    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // Gui tin nhan di
        try{
            if(yeucau.equals("ChatWithGroup")){
                out.writeUTF(yeucau);
                out.writeUTF("Text");
                out.writeInt(numFri);
                for(String nameF: friends.keySet())
                    out.writeUTF(nameF);
                out.writeUTF(txtMessage.getText());
                out.flush();
            }else if(yeucau.equals("ChatWithFriend")){
                out.writeUTF(yeucau);
                out.writeUTF("Text");
                out.writeUTF(lblName.getText());
                out.writeUTF(txtMessage.getText());
                out.flush();
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
        
        //In message len panel_Chat
        JPanel panel = Panel_Message();
        setLayOut_RIGHT(panel);
        JLabel mess = Message(txtMessage.getText());
        JLabel avatar = Avatar_User();
        mess.setVisible(true);
        avatar.setVisible(true);
        panel.setVisible(true);
        
        panel.add(mess);
        panel.add(avatar);
       
        
        
        DisplayMessage(panel);

        txtMessage.setText("");
        
        autoScroll();
    }//GEN-LAST:event_btnSendActionPerformed

    //Xử lý sự kiện chatGroup
    private void lbl_GroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_GroupMouseClicked
        yeucau = "ChatWithGroup";
        setFoucus(lbl_Group);
        resetFoucus(lbl_Chat, lbl_Add, lbl_Logout);
         
    }//GEN-LAST:event_lbl_GroupMouseClicked

    //Các xử lý cho việc hiển thị lên khung chat và gữi đi
    private void Label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label1MouseClicked

        Add_EmojisToPanelChatforUser(Label1.getIcon().toString());
        try {
            sendEmojis(Label1.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label1MouseClicked

    private void Label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label2MouseClicked
        
        Add_EmojisToPanelChatforUser(Label2.getIcon().toString());
        try {
            sendEmojis(Label2.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label2MouseClicked

    private void Label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label3MouseClicked
        
        Add_EmojisToPanelChatforUser(Label3.getIcon().toString());
        try {
            sendEmojis(Label3.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label3MouseClicked

    private void Label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label4MouseClicked
        
        Add_EmojisToPanelChatforUser(Label4.getIcon().toString());
        try {
            sendEmojis(Label4.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_Label4MouseClicked

    private void Label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label5MouseClicked
        
        Add_EmojisToPanelChatforUser(Label5.getIcon().toString());
        try {
            sendEmojis(Label5.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label5MouseClicked

    private void Label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label6MouseClicked
        
        Add_EmojisToPanelChatforUser(Label6.getIcon().toString());
        try {
            sendEmojis(Label6.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label6MouseClicked

    private void Label7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label7MouseClicked
        
        Add_EmojisToPanelChatforUser(Label7.getIcon().toString());
        try {
            sendEmojis(Label7.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label7MouseClicked

    private void Label8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label8MouseClicked
        
        Add_EmojisToPanelChatforUser(Label8.getIcon().toString());
        try {
            sendEmojis(Label8.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label8MouseClicked

    private void Label9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label9MouseClicked
        
        Add_EmojisToPanelChatforUser(Label9.getIcon().toString());
        try {
            sendEmojis(Label9.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label9MouseClicked

    private void Label10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label10MouseClicked
        
        Add_EmojisToPanelChatforUser(Label10.getIcon().toString());
        try {
            sendEmojis(Label10.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label10MouseClicked

    private void Label11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label11MouseClicked
        
        Add_EmojisToPanelChatforUser(Label11.getIcon().toString());
        try {
            sendEmojis(Label11.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label11MouseClicked

    private void Label12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label12MouseClicked
        
        Add_EmojisToPanelChatforUser(Label12.getIcon().toString());
        try {
            sendEmojis(Label12.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label12MouseClicked

    private void Label13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label13MouseClicked
        
        Add_EmojisToPanelChatforUser(Label13.getIcon().toString());
        try {
            sendEmojis(Label13.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label13MouseClicked

    private void Label14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label14MouseClicked
        
        Add_EmojisToPanelChatforUser(Label14.getIcon().toString());
        try {
            sendEmojis(Label14.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label14MouseClicked

    private void Label15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label15MouseClicked
        
        Add_EmojisToPanelChatforUser(Label15.getIcon().toString());
        try {
            sendEmojis(Label15.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label15MouseClicked

    private void Label16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label16MouseClicked
        
        Add_EmojisToPanelChatforUser(Label16.getIcon().toString());
        try {
            sendEmojis(Label16.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label16MouseClicked

    private void Label17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label17MouseClicked
        
        Add_EmojisToPanelChatforUser(Label17.getIcon().toString());
        try {
            sendEmojis(Label17.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label17MouseClicked

    private void Label18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label18MouseClicked
        
        Add_EmojisToPanelChatforUser(Label18.getIcon().toString());
        try {
            sendEmojis(Label18.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label18MouseClicked

    private void Label19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label19MouseClicked
        
        Add_EmojisToPanelChatforUser(Label19.getIcon().toString());
        try {
            sendEmojis(Label19.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label19MouseClicked

    private void Label20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label20MouseClicked
        
        Add_EmojisToPanelChatforUser(Label20.getIcon().toString());
        try {
            sendEmojis(Label20.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label20MouseClicked

    private void Label21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label21MouseClicked
        
        Add_EmojisToPanelChatforUser(Label21.getIcon().toString());
        try {
            sendEmojis(Label21.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label21MouseClicked

    private void Label22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label22MouseClicked
        
        Add_EmojisToPanelChatforUser(Label22.getIcon().toString());
        try {
            sendEmojis(Label22.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label22MouseClicked

    private void Label23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label23MouseClicked

        Add_EmojisToPanelChatforUser(Label23.getIcon().toString());
        try {
            sendEmojis(Label23.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label23MouseClicked

    private void Label24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label24MouseClicked
        
        Add_EmojisToPanelChatforUser(Label24.getIcon().toString());
        try {
            sendEmojis(Label24.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label24MouseClicked

    private void Label25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label25MouseClicked
        
        Add_EmojisToPanelChatforUser(Label25.getIcon().toString());
        try {
            sendEmojis(Label25.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label25MouseClicked

    private void Label26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label26MouseClicked
        
        Add_EmojisToPanelChatforUser(Label26.getIcon().toString());
        try {
            sendEmojis(Label26.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label26MouseClicked

    private void Label27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label27MouseClicked
        
        Add_EmojisToPanelChatforUser(Label27.getIcon().toString());
        try {
            sendEmojis(Label27.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_Label27MouseClicked

    private void Label28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label28MouseClicked
        
        Add_EmojisToPanelChatforUser(Label28.getIcon().toString());
        try {
            sendEmojis(Label28.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label28MouseClicked

    private void Label29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label29MouseClicked
        
        Add_EmojisToPanelChatforUser(Label29.getIcon().toString());
        try {
            sendEmojis(Label29.getIcon().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Label29MouseClicked

    public final void sendEmojis(String s) throws IOException{
            if(yeucau.equals("ChatWithGroup")){
                out.writeUTF(yeucau);
                out.writeUTF("Emojis");
                out.writeInt(numFri);
                for(String nameF: friends.keySet())
                    out.writeUTF(nameF);
                out.writeUTF(s);
                out.flush();
            }else if(yeucau.equals("ChatWithFriend")){
                out.writeUTF(yeucau);
                out.writeUTF("Emojis");
                out.writeUTF(lblName.getText());
                out.writeUTF(s);
                out.flush();
            }        
//        out.writeUTF(yeucau);
//        out.writeUTF("Emojis");
//        out.writeUTF(lblName.getText());
//        out.writeUTF(s);
//        out.flush();
        
    }
    
    private void lblAvatar_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatar_UserMouseClicked
        
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Profile_From profile = new Profile_From(nameuser, gioitinh, ngaysinh, avatar);
                profile.setVisible(true);
                profile.setLocationRelativeTo(null);
            }
        });
        
    }//GEN-LAST:event_lblAvatar_UserMouseClicked

    //Xử lý sự kiện Logout
    private void lbl_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogoutMouseClicked
        setFoucus(lbl_Logout);
        resetFoucus(lbl_Chat, lbl_Group, lbl_Add);
        
        try{
           out.writeUTF("Log out");
           out.flush();
           
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    LoginFrom login = new LoginFrom();
                    login.setVisible(true);
                    login.setLocationRelativeTo(null);
                }
            });
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        this.setVisible(false);
        
    }//GEN-LAST:event_lbl_LogoutMouseClicked

    //Xử lý sự kiện phím Enter
    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
        btnSendActionPerformed(evt);
        
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnDSBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSBanActionPerformed
        
        friends = new HashMap<String, String> (); 
        
        try {
            database.Connection();
        
            String executeStr = "Select MaUserFriend from Friend where MaUser = " + mauser + ";";
            ResultSet rs = database.executeQuery(executeStr);
            while(rs.next()){
                String executeStr1 = "Select NameUser, Avatar from Users where MaUser = " + rs.getInt(1) + ";";
                ResultSet rs1 = database.executeQuery(executeStr1);
                while(rs1.next()) {
                    friends.put(rs1.getString(1), rs1.getString(2));
                    JPanel panel = PanelFriend(rs1.getString(1), rs1.getString("Avatar"));
                    Panel_ListFriend.add(panel);
                    Panel_ListFriend.validate();
                    System.out.println(rs1.getString(1));
                    System.out.println(rs1.getString(2));
                    numFri++;
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        if(numFri > 0)
            btnDSBan.setEnabled(false);
    }//GEN-LAST:event_btnDSBanActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String nameFriend = txtSearch.getText();
        SetUp_PanelFriend(nameFriend, friends.get(nameFriend));
        PanelChat.removeAll();
        PanelChat.validate();
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lbl_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddMouseClicked
        setFoucus(lbl_Add);
        resetFoucus(lbl_Chat, lbl_Group, lbl_Logout);
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    AddFriendFrom add = new AddFriendFrom(mauser);
                    add.setVisible(true);
                    add.setLocationRelativeTo(null);
                }
            });
        
    }//GEN-LAST:event_lbl_AddMouseClicked

    private void lbl_ChonFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChonFileMouseClicked
        // Hiển thị hộp thoại cho người dùng chọn file để gửi
        JFileChooser fileChooser = new JFileChooser();
        int rVal = fileChooser.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            byte[] selectedFile = new byte[(int) fileChooser.getSelectedFile().length()];
            BufferedInputStream bis;
            try {
		bis = new BufferedInputStream(new FileInputStream(fileChooser.getSelectedFile()));
		// Đọc file vào biến selectedFile
		bis.read(selectedFile, 0, selectedFile.length);
						
		out.writeUTF("File");
		out.writeUTF(lblName.getText());
		out.writeUTF(fileChooser.getSelectedFile().getName());
		out.writeUTF(String.valueOf(selectedFile.length));
						
		int size = selectedFile.length;
		int bufferSize = 2048;
		int offset = 0;
						
		// Lần lượt gửi cho server từng buffer cho đến khi hết file
		while (size > 0) {
                    out.write(selectedFile, offset, Math.min(size, bufferSize));
                    offset += Math.min(size, bufferSize);
                    size -= bufferSize;
		} 
						
		out.flush();
						
		bis.close();
						
		// In ra màn hình file
		JPanel panel = Panel_Message();
                setLayOut_RIGHT(panel);
                JLabel mess = Message(fileChooser.getSelectedFile().getName());
                JLabel avatar = Avatar_User();
                mess.setVisible(true);
                avatar.setVisible(true);
                panel.setVisible(true);

                panel.add(mess);
                panel.add(avatar);
       
                DisplayMessage(panel);
            } catch (IOException e1) {
		e1.printStackTrace();
            }
        }
    }//GEN-LAST:event_lbl_ChonFileMouseClicked
    
    //Hiển thị Emojis lên khung chat từ phía Friend
    private void Add_EmojisToPanelChatforFriend(String path, String avatarFriend) {
        JPanel panel = Panel_Message();
        setLayOut_LEFT(panel);
        
        JLabel avatar = Avatar_Friend(avatarFriend);
        JLabel emojis = new JLabel();
        ImageIcon icon = new ImageIcon(path);
        emojis.setIcon(icon);
        avatar.setVisible(true);
        emojis.setVisible(true);
        
        panel.add(avatar);
        panel.add(emojis);
        
        PanelChat.add(panel);
        PanelChat.validate();
        ScrollPane_Chat.validate();
        
        autoScroll();
    }
    
    //Hiển thị Emojis lên khung chat từ phía User
    private void Add_EmojisToPanelChatforUser(String path) {
        JPanel panel = Panel_Message();
        setLayOut_RIGHT(panel);
        
        JLabel avatar = Avatar_User();
        JLabel emojis = new JLabel();
        ImageIcon icon = new ImageIcon(path);
        emojis.setIcon(icon);
        avatar.setVisible(true);
        emojis.setVisible(true);
        
        panel.add(emojis);
        panel.add(avatar);
        
        PanelChat.add(panel);
        PanelChat.validate();
        ScrollPane_Chat.validate();
        
        autoScroll();
        
        
    }
   
    //Xử lý sự kiện tự cuộn của khung chat
    public final void autoScroll() {
	ScrollPane_Chat.getVerticalScrollBar().setValue(ScrollPane_Chat.getVerticalScrollBar().getMaximum());

    }
    
    
    //Tao Panel để chứa Thông tin của Friend
    public final JPanel PanelFriend(String namef, String pathAvatar) {
        JPanel panel = new JPanel();
        panel.setSize(260, 60);
        panel.setBackground(Color.white);
        panel.setBorder(BorderFactory.createEtchedBorder());
        
        JLabel name = Name(namef);
        JLabel avatar1 = Avatar_Friend(pathAvatar);
        name.setVisible(true);
        avatar1.setVisible(true);
        
        
        panel.add(avatar1);
        panel.add(name);
        panel.validate();
        
        
        return panel;
    }
    
    //Tạo Label chứa Name
    public final JLabel Name(String name) {
        JLabel Name = new JLabel();
        Name.setFont(new Font("Times New Roman", 0, 18));
        Name.setText(name);
        
        return Name;
    }
    
    //Tạo Label chứa Avatar_User
    public final JLabel Avatar_User() {
        JLabel avatar = new JLabel();
        avatar.setSize(50, 50);
        ImageIcon icon3 = EditImage.XuLyAnh.Edit_Img(this.avatar, avatar);        
        avatar.setIcon(icon3);
        
        return avatar;
    }
    
    //Tạo Label chứa Avatar_Friend
    public final JLabel Avatar_Friend(String pathAvatar) {
        JLabel avatar = new JLabel();
        avatar.setSize(50, 50);
        ImageIcon icon3 = EditImage.XuLyAnh.Edit_Img(pathAvatar, avatar); 
        avatar.setBorder(BorderFactory.createEtchedBorder());
        avatar.setIcon(icon3);
        
        return avatar;
    }
       
    
    //Tạo Label message
    public final JLabel Message(String mess) {
        JLabel message = new JLabel();
        message.setFont(new Font("Times New Roman", 0, 18));
        message.setText(mess);
        
        return message;
    }
    
    //Tạo Panel chứa Message
    public final JPanel Panel_Message() {
        JPanel panel = new JPanel();
        panel.setSize(800, 70);
        panel.setBackground(Color.white);      

        return panel;
    }
    
    //Hiển Thị tin nhắn lên màn hình
    public final void DisplayMessage(JPanel panel){

        PanelChat.add(panel);
        
        PanelChat.validate();
        ScrollPane_Chat.validate();
        
        
    }
    
    //Set layout để hiển thị panel của phía Friend
    public final void setLayOut_LEFT(JPanel panel){
        
        FlowLayout layout = new FlowLayout();
        layout.setAlignment(FlowLayout.LEFT);
        panel.setLayout(layout);
        
    }
    
    //Set layout để hiển thị panel của phía user
    public final void setLayOut_RIGHT(JPanel panel){
        
        FlowLayout layout = new FlowLayout();
        layout.setAlignment(FlowLayout.RIGHT);
        panel.setLayout(layout);
        
    }
    
    
    
    
    /*Tạo một luồng nhận tin nhắn
    
    */
    
    class Receiver implements Runnable {

        private DataInputStream in;
        
        public Receiver(DataInputStream in) {
            this.in = in;
        }
        
        @Override
        public void run() {
            
            try {
                
                while(true){
                    
                    //Chờ tin nhắn từ server
                    String styleMess = in.readUTF();
                    
                    if(styleMess.equals("Text")) {
                        //Nhận tin nhắn văn bản
                        String pathAvatar = in.readUTF();
                        String message = in.readUTF();
                        String nameFriend = in.readUTF();
                        
                        //In message len panel_Chat
                        SetUp_PanelFriend(nameFriend, pathAvatar);
                        
                        JPanel panel = Panel_Message();
                        setLayOut_LEFT(panel);
                        JLabel mess = Message(message);
                        JLabel avatar = Avatar_Friend(pathAvatar);
                        mess.setVisible(true);
                        avatar.setVisible(true);
                        panel.setVisible(true);

                        panel.add(avatar);
                        panel.add(mess);
                        
                        

                        DisplayMessage(panel);
                        
                        autoScroll();
                    }
                    else if(styleMess.equals("Emojis")) {
                        //Nhận tin nhắn Emojis
                        String pathAvatar = in.readUTF();
                        String emojis = in.readUTF();
                        String nameFriend = in.readUTF();
                        
                        SetUp_PanelFriend(nameFriend, pathAvatar);
                        //Hiển thị emojis lên khung chat
                        Add_EmojisToPanelChatforFriend(emojis, pathAvatar);
                        
                    }
                    else if(styleMess.equals("File")){
                        
                    }
                    
                    else if(styleMess.equals("da dang xuat")){
                        JOptionPane.showMessageDialog(null, "Bạn đã thoát.", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                        
                    }
                    
                }
                
            }catch(Exception e){
                e.printStackTrace();
            }finally{
                try {
                   if(in != null){
                       in.close();
                   } 
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label15;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label17;
    private javax.swing.JLabel Label18;
    private javax.swing.JLabel Label19;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label20;
    private javax.swing.JLabel Label21;
    private javax.swing.JLabel Label22;
    private javax.swing.JLabel Label23;
    private javax.swing.JLabel Label24;
    private javax.swing.JLabel Label25;
    private javax.swing.JLabel Label26;
    private javax.swing.JLabel Label27;
    private javax.swing.JLabel Label28;
    private javax.swing.JLabel Label29;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JPanel PanelChat;
    private javax.swing.JPanel PanelChucNang;
    private javax.swing.JPanel Panel_Contain;
    private javax.swing.JPanel Panel_Emojis;
    private javax.swing.JPanel Panel_ListFriend;
    private javax.swing.JPanel Panel_Name_Friend;
    private javax.swing.JPanel Panel_NhapText;
    private javax.swing.JPanel Panel_Search;
    private javax.swing.JScrollPane ScrollPane_Chat;
    private javax.swing.JScrollPane ScrollPane_Emojis;
    private javax.swing.JScrollPane ScrollPanel_listFiend;
    private javax.swing.JButton btnDSBan;
    private javax.swing.JButton btnDSNhom;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel lblAvatar_Friend;
    private javax.swing.JLabel lblAvatar_User;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbl_Add;
    private javax.swing.JLabel lbl_Chat;
    private javax.swing.JLabel lbl_ChonFile;
    private javax.swing.JLabel lbl_Group;
    private javax.swing.JLabel lbl_Heading;
    private javax.swing.JLabel lbl_Logout;
    private javax.swing.JPanel panelContain;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}